#!/bin/sh

cd /backup/baal

# Unlink the oldest snapshot
if [ -d 4 ] ; then
  /bin/rm 4
fi

# Rotate all the other snapshots forward
if [ -d 3 ] ; then /bin/mv 3 4; fi
if [ -d 2 ] ; then /bin/mv 2 3; fi
if [ -d 1 ] ; then /bin/mv 1 2; fi
if [ -d 0 ] ; then /bin/mv 0 1; fi

# Make a new empty directory for 0/
/bin/mkdir 0
